#!/usr/bin/env python

#----------------------------------------------------------------------#
# filename: pyfits+psycopg2_ex.py 
# author: Peter Nugent
# date: 10/30/2014
# ---------------------------------------------------------------------#
# Function: Read in a Arjun fits binary table from standard in and load it
# into the desi calib pg table database with psycopg2.
# ---------------------------------------------------------------------#

# First, we'll load up the dependencies:

# psycopg2 is an open-source postgres client for python. 
# We may want db access at some point and, of course, pyfits & sys

import psycopg2 

import astropy
from astropy.io import fits

import sys, os, re, glob
import numpy as np


# Read in the image name (ooi) and create the mask (ood) and weight (oow) names

fitsbin = str(sys.argv[1])

# First, open the table using pyfits:

table = fits.open( fitsbin )


# Access the data part of the table.

tbdata = table[1].data
tbdata = np.asarray(tbdata)

# determine the number of elements 

nrows = tbdata.shape[0] 
newdata = []

# Fire up the db

con = psycopg2.connect(host='scidb2.nersc.gov', user='desi_admin', password='L00cy-1959', database='desi')
cursor = con.cursor()

# Re-cast as strings so the load is easy 

for i in range(0, nrows):
   

    line = [ tbdata['EXPNUM'][i], tbdata['CCDNUM'][i], tbdata['CCDZPT'][i], tbdata['CCDPHRMS'][i], tbdata['CCDSKYRMS'][i], tbdata['CCDNSTAR'][i], tbdata['CCDNMATCH'][i], tbdata['CCDMDNCOL'][i] ]

    newdata.append(line) 

## Re-cast as strings so the load is easy 
#
for i, f in enumerate(newdata):
##
   query = 'INSERT INTO zp ( EXPNUM, CCDNUM, CCDZPT, CCDPHRMS, CCDSKYRMS, CCDNSTAR, CCDNMATCH, CCDMDNCOL ) VALUES ( %s, %s, %s, %s, %s, %s, %s, %s )' 
##
   cursor.execute( query, tuple( [str(elem) for elem in newdata[i]] ) ) 
#
#

con.commit()

# That's it!

